name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  path: ^1.8.3
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  provider: ^6.0.5
  image_picker: ^1.0.4
  video_player: ^2.7.2
  firebase_storage: ^11.2.8
  google_sign_in: ^6.1.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_iconpicker: ^3.2.4
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  app_usage: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - lib/resources/assets/svg/
  fonts:
    - family: 'mainFont'
      fonts:
        - asset: lib/resources/assets/fonts/Heebo-VariableFont_wght.ttf
    - family: 'secondFont'
      fonts:
        - asset: lib/resources/assets/fonts/Pacifico-Regular.ttf
